name: CI - Build & Push

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: yalp/test-shared-workflow/.github/workflows/shared.yml@main
    with:
      version: "1.0.0"
      environment: "test"
    secrets: inherit
